<?php
use \page\RespTheme\Customize;
use \page\RespTheme\LogInAndLogOut;
use \page\RespTheme\PrimaryNavigationComp;
use \page\RespTheme\CommonPrimarySettings;
use \Facebook\WebDriver\Remote\RemoteWebDriver;
use \Facebook\WebDriver\WebDriverBy;
use \Facebook\WebDriver\WebDriverKeys;

class PrimaryNavigationCest
{
    public function _before(RespThemeTester $I, LogInAndLogOut $loginAndLogout, Customize $customize, PrimaryNavigationComp $primaryNavigationComp, CommonPrimarySettings $helper )
    {
        
        $I->amGoingTo('Login as Admin');
        $loginAndLogout->userLogin($I);

       
        $I->click($customize->url);
        $I->wait(2);
        $I->scrollTo($customize->header);
        $I->wait(2);
        $I->click($customize->header);
        $I->wait(2);
        $I->click($primaryNavigationComp->primaryNavButton);
    }

    // tests
public function PrimaryNavigationStyle(RespThemeTester $I, LogInAndLogOut $loginAndLogout, Customize $customize, PrimaryNavigationComp $primaryNavigationComp, CommonPrimarySettings $helper)
   {
    $I->amGoingTo('check the primary navigation style settings for primary navigation');
    $I->click($primaryNavigationComp->strechPMenu);
    $I->wait(2);
   $I->selectOption($primaryNavigationComp->primaryNavigationStyle, 'Standard');
    $I->wait(1);
    $I->click($primaryNavigationComp->desktop);
    $I->wait(2);
    $I->click($primaryNavigationComp->publishButton);
    $I->wait(3);
    $I->amGoingTo('check on the front end');
    $I->amOnPage('/');
    $I->wait(2);
    $I->assertEquals($primaryNavigationComp->primaryNavigationStyle,$helper->navigationStyle);
    $I->wait(2);
    $I->seeElement($primaryNavigationComp->deskrow);
    $I->wait(2);
    
    $I->click($customize->url);
    $I->wait(2);
    $I->scrollTo($customize->header);
    $I->wait(2);
    $I->click($customize->header);
    $I->wait(2);
    $I->click($primaryNavigationComp->primaryNavButton);
    $I->selectOption($primaryNavigationComp->primaryNavigationStyle, 'Full height');
    $I->wait(1);
    $I->click($primaryNavigationComp->desktop);
    $I->wait(2);
    $I->click($primaryNavigationComp->publishButton);
    $I->wait(3);
    $I->amGoingTo('check on the front end');
    $I->amOnPage('/');
    $I->wait(2);
    $I->assertEquals($primaryNavigationComp->primaryNavigationStyle,$helper->navigationStyle);
    $I->wait(2);
    $I->seeElement($primaryNavigationComp->deskrow);
    $I->wait(2);
    
    $I->click($customize->url);
    $I->wait(2);
    $I->scrollTo($customize->header);
    $I->wait(2);
    $I->click($customize->header);
    $I->wait(2);
    $I->click($primaryNavigationComp->primaryNavButton);
    $I->selectOption($primaryNavigationComp->primaryNavigationStyle, 'Underline');
    $I->wait(1);
    $I->click($primaryNavigationComp->desktop);
    $I->wait(2);
    $I->click($primaryNavigationComp->publishButton);
    $I->wait(3);
    $I->amGoingTo('check on the front end');
    $I->amOnPage('/');
    $I->wait(2);
    $I->assertEquals($primaryNavigationComp->primaryNavigationStyle,$helper->navigationStyle);
    $I->wait(2);
    $I->seeElement($primaryNavigationComp->deskrow);
    $I->wait(2);
    

    $I->click($customize->url);
    $I->wait(2);
    $I->scrollTo($customize->header);
    $I->wait(2);
    $I->click($customize->header);
    $I->wait(2);
    $I->click($primaryNavigationComp->primaryNavButton);
    $I->selectOption($primaryNavigationComp->primaryNavigationStyle, 'Underline - Full height');
    $I->wait(1);
    $I->click($primaryNavigationComp->desktop);
    $I->wait(2);
    $I->click($primaryNavigationComp->publishButton);
    $I->wait(3);
    $I->amGoingTo('check on the front end');
    $I->amOnPage('/');
    $I->assertEquals($primaryNavigationComp->primaryNavigationStyle,$helper->navigationStyle);
    $I->wait(2);
    $I->seeElement($primaryNavigationComp->deskrow);
    $I->wait(2);

    $I->amGoingTo('Logout');
       $loginAndLogout->userLogout($I);
       $I->wait(2);

    }
    public function ItemSettings(RespThemeTester $I, LogInAndLogOut $loginAndLogout, Customize $customize, PrimaryNavigationComp $primaryNavigationComp, CommonPrimarySettings $helper)
    {
        $I->amGoingTo('check the Itemspacing and vertical itemspacing settings for primary navigation');
        $I->fillField($primaryNavigationComp->itemSpacing, '46');
        $I->wait(1);
        $I->fillField($primaryNavigationComp->itemVerticalSpacing, '34');
        $I->wait(1);
         $I->click($primaryNavigationComp->desktop);
         $I->wait(2);
         $I->click($primaryNavigationComp->publishButton);
         $I->wait(3);
         $I->amGoingTo('check on the front end');
         $I->amOnPage('/');
         $I->wait(2);
         $helper->_checkStyle($I,$helper->itemspacing,'padding','xpath','34px 46px');
         $I->wait(2);
         
         $I->amGoingTo('check the Item color settings for primary navigation');
        $I->click($customize->url);
        $I->wait(2);
        $I->scrollTo($customize->header);
        $I->wait(2);
        $I->click($customize->header);
        $I->wait(2);
        $I->click($primaryNavigationComp->primaryNavButton);
         $I->click($primaryNavigationComp->selectItemColor);
          $I->wait(1);
          $I->click($primaryNavigationComp->itemColor);
          $I->wait(1);
          $I->click($primaryNavigationComp->desktop);
          $I->wait(2);
          $I->click($primaryNavigationComp->publishButton);
          $I->wait(3);
          $I->amGoingTo('check on the front end');
          $I->amOnPage('/');
          $I->wait(2);
          $helper->_checkStyle($I,$helper->pItemColor,'color','xpath','rgb(221, 51, 51)');
         $I->wait(2);

          $I->amGoingTo('check the Item hover  color settings for primary navigation');
          $I->click($customize->url);
          $I->wait(2);
          $I->scrollTo($customize->header);
          $I->wait(2);
          $I->click($customize->header);
          $I->wait(2);
          $I->click($primaryNavigationComp->primaryNavButton);
          $I->wait(2);
          $I->scrollTo($primaryNavigationComp->selectHoverItem);
          $I->wait(1);
           $I->click($primaryNavigationComp->selectHoverItem);
            $I->wait(1);
            $I->click($primaryNavigationComp->hoverItemColor);
            $I->wait(1);
            $I->click($primaryNavigationComp->desktop);
            $I->wait(2);
            $I->click($primaryNavigationComp->publishButton);
            $I->wait(3);
            $I->switchToIFrame($helper->frame);
            $I->wait(1);
            $I->moveMouseOver($primaryNavigationComp->samplepage);
            $I->wait(2);
            $I->switchToIFrame();
            $I->amGoingTo('check on the front end');
            $I->amOnPage('/');
            $I->wait(2);
            $helper->_checkStyle($I,$helper->pItemColor,'color','xpath','rgb(221, 51, 51)');
            $I->wait(2);
            $I->moveMouseOver($primaryNavigationComp->samplepage);
            $I->wait(2);
            
           $I->amGoingTo('check the Active Item  color settings for primary navigation');
          $I->click($customize->url);
          $I->wait(2);
          $I->scrollTo($customize->header);
          $I->wait(2);
          $I->click($customize->header);
          $I->wait(2);
          $I->click($primaryNavigationComp->primaryNavButton);
           $I->click($primaryNavigationComp->selectActiveItemColor);
            $I->wait(1);
            $I->click($primaryNavigationComp->activeItemColor);
            $I->wait(1);
            $I->click($primaryNavigationComp->desktop);
            $I->wait(2);
            $I->click($primaryNavigationComp->publishButton);
            $I->wait(3);
            $I->amGoingTo('check on the front end');
            $I->amOnPage('/');
            $I->wait(2);
            $helper->_checkStyle($I,$helper->pActiveItemColor,'color','xpath','rgb(221, 153, 51)');
            $I->wait(2);
            
            $I->amGoingTo('check the Background color settings for primary navigation');
            $I->click($customize->url);
            $I->wait(2);
            $I->scrollTo($customize->header);
            $I->wait(2);
            $I->click($customize->header);
            $I->wait(2);
            $I->click($primaryNavigationComp->primaryNavButton);
             $I->click($primaryNavigationComp->selectBackgroundColor);
              $I->wait(1);
              $I->click($primaryNavigationComp->backgroundColor);
              $I->wait(1);
              $I->click($primaryNavigationComp->desktop);
              $I->wait(2);
              $I->click($primaryNavigationComp->publishButton);
              $I->wait(3);
              $I->amGoingTo('check on the front end');
              $I->amOnPage('/');
              $I->wait(2);
              $helper->_checkStyle($I,$helper->pBackgroundColor,'background','xpath','rgb(30, 115, 190) none repeat scroll 0% 0%');
              $I->wait(2);
              
        
              $I->amGoingTo('check the Background hover color settings for primary navigation');
              $I->click($customize->url);
              $I->wait(2);
              $I->scrollTo($customize->header);
              $I->wait(2);
              $I->click($customize->header);
              $I->wait(2);
              $I->click($primaryNavigationComp->primaryNavButton);
               $I->click($primaryNavigationComp->selectBgHoverColor);
                $I->wait(1);
                $I->click($primaryNavigationComp->bgHoverColor);
                $I->wait(1);
                $I->click($primaryNavigationComp->desktop);
                $I->wait(2);
                $I->click($primaryNavigationComp->publishButton);
                $I->wait(3);
                $I->switchToIFrame($helper->frame);
                $I->wait(1);
                $I->moveMouseOver($primaryNavigationComp->samplepage);
                $I->wait(2);
                $I->switchToIFrame();
                $I->amGoingTo('check on the front end');
                $I->amOnPage('/');
                $I->wait(2);
               $helper->_checkStyle($I,$helper->pBgHoverColor,'background','xpath','rgb(30, 115, 190) none repeat scroll 0% 0%');
                $I->wait(2);
              $I->moveMouseOver($primaryNavigationComp->samplepage);
              $I->wait(2);

                $I->amGoingTo('check the Active background  color settings for primary navigation');
                $I->click($customize->url);
                $I->wait(2);
                $I->scrollTo($customize->header);
                $I->wait(2);
                $I->click($customize->header);
                $I->wait(2);
                $I->click($primaryNavigationComp->primaryNavButton);
                $I->click($primaryNavigationComp->selectActiveBgColor);
                $I->wait(1);
                $I->click($primaryNavigationComp->activeBgColor);
                $I->wait(1);
                $I->click($primaryNavigationComp->desktop);
                $I->wait(2);
                $I->click($primaryNavigationComp->publishButton);
                $I->wait(3);
                $I->amGoingTo('check on the front end');
                $I->amOnPage('/');
                $I->wait(2);
                $helper->_checkStyle($I,$helper->pActiveBgColor,'background','xpath','rgb(30, 115, 190) none repeat scroll 0% 0%');
                $I->wait(2);

                $I->amGoingTo('Logout');
               $loginAndLogout->userLogout($I);
               $I->wait(2);
                  
    }

    public function DropdownSettings(RespThemeTester $I, LogInAndLogOut $loginAndLogout, Customize $customize, PrimaryNavigationComp $primaryNavigationComp, CommonPrimarySettings $helper)
    {
      $I->amGoingTo('check the dropdown reveal settings for primary navigation');
      $I->scrollTo($primaryNavigationComp->dropdownReveal);
        $I->selectOption($primaryNavigationComp->dropdownReveal, 'Fade');
        $I->wait(1);
        $I->click($primaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($primaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($primaryNavigationComp->home);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $I->assertEquals($primaryNavigationComp->dropdownReveal,$helper->dDReveal);
        $I->wait(2);
        $I->moveMouseOver($primaryNavigationComp->home);
        $I->wait(2);
        

        $I->click($customize->url);
        $I->wait(2);
        $I->scrollTo($customize->header);
        $I->wait(2);
        $I->click($customize->header);
        $I->wait(2);
        $I->click($primaryNavigationComp->primaryNavButton);
        $I->selectOption($primaryNavigationComp->dropdownReveal, 'None');
        $I->wait(1);
        $I->click($primaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($primaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($primaryNavigationComp->home);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $I->assertEquals($primaryNavigationComp->dropdownReveal,$helper->dDReveal);
        $I->wait(2);
        $I->moveMouseOver($primaryNavigationComp->home);
        $I->wait(2);
        
        
        $I->click($customize->url);
        $I->wait(2);
        $I->scrollTo($customize->header);
        $I->wait(2);
        $I->click($customize->header);
        $I->wait(2);
        $I->click($primaryNavigationComp->primaryNavButton);
        $I->selectOption($primaryNavigationComp->dropdownReveal, 'Fade Up');
        $I->wait(1);
        $I->click($primaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($primaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($primaryNavigationComp->home);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $I->assertEquals($primaryNavigationComp->dropdownReveal,$helper->dDReveal);
        $I->wait(2);
        $I->moveMouseOver($primaryNavigationComp->home);
        $I->wait(2);
        
        $I->click($customize->url);
        $I->wait(2);
        $I->scrollTo($customize->header);
        $I->wait(2);
        $I->click($customize->header);
        $I->wait(2);
        $I->click($primaryNavigationComp->primaryNavButton);
        $I->selectOption($primaryNavigationComp->dropdownReveal, 'Fade Down');
        $I->wait(1);
        $I->click($primaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($primaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($primaryNavigationComp->home);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $I->assertEquals($primaryNavigationComp->dropdownReveal,$helper->dDReveal);
        $I->wait(2);
        $I->moveMouseOver($primaryNavigationComp->home);
        $I->wait(2);

        $I->amGoingTo('Check drop down width settings for primary navigation');
        $I->click($customize->url);
        $I->wait(2);
        $I->scrollTo($customize->header);
        $I->wait(2);
        $I->click($customize->header);
        $I->wait(2);
        $I->click($primaryNavigationComp->primaryNavButton);
        $I->fillField($primaryNavigationComp->dropdownWidth, '213');
        $I->wait(1);
        $I->click($primaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($primaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($primaryNavigationComp->home);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->dWidth,'width','xpath','213px');
        $I->wait(2);
        $I->moveMouseOver($primaryNavigationComp->home);
        $I->wait(2); 

          $I->amGoingTo('Check dropdown vertical spacing settings for primary navigation');
          $I->click($customize->url);
          $I->wait(2);
          $I->scrollTo($customize->header);
          $I->wait(2);
          $I->click($customize->header);
          $I->wait(2);
          $I->click($primaryNavigationComp->primaryNavButton);
          $I->scrollTo($primaryNavigationComp->dropdownVerticalSpacing);
          $I->wait(1);
          $I->fillField($primaryNavigationComp->dropdownVerticalSpacing, '21');
          $I->wait(1);
          $I->click($primaryNavigationComp->desktop);
          $I->wait(2);
          $I->click($primaryNavigationComp->publishButton);
          $I->wait(3);
          $I->switchToIFrame($helper->frame);
          $I->wait(1);
          $I->moveMouseOver($primaryNavigationComp->home);
          $I->wait(2);
          $I->switchToIFrame();
          $I->amGoingTo('check on the front end');
          $I->amOnPage('/');
          $I->wait(2);
          $helper->_checkStyle($I,$helper->dVerSpacing,'padding-top','xpath','21px');
          $I->wait(2);
          $I->moveMouseOver($primaryNavigationComp->home);
          $I->wait(2); 
           

            $I->amGoingTo('Check dropdown item divider style settings for primary navigation');
            $I->click($customize->url);
            $I->wait(2);
            $I->scrollTo($customize->header);
            $I->wait(2);
            $I->click($customize->header);
            $I->wait(2);
            $I->click($primaryNavigationComp->primaryNavButton);
            $I->scrollTo($primaryNavigationComp->dropdownDividerStyle);
            $I->wait(1);
            $I->selectOption($primaryNavigationComp->dropdownDividerStyle, 'Dashed');
            $I->wait(1);
            $I->click($primaryNavigationComp->desktop);
            $I->wait(2);
            $I->click($primaryNavigationComp->publishButton);
            $I->wait(3);
            $I->switchToIFrame($helper->frame);
            $I->wait(1);
            $I->moveMouseOver($primaryNavigationComp->home);
            $I->wait(2);
            $I->switchToIFrame();
            $I->amGoingTo('check on the front end');
            $I->amOnPage('/');
            $I->assertEquals($primaryNavigationComp->dropdownDividerStyle,$helper->dividerStyle);
            $I->wait(2);
            $I->moveMouseOver($primaryNavigationComp->home);
            $I->wait(2);
        
            $I->click($customize->url);
            $I->wait(2);
            $I->scrollTo($customize->header);
            $I->wait(2);
            $I->click($customize->header);
            $I->wait(2);
            $I->click($primaryNavigationComp->primaryNavButton);
            $I->scrollTo($primaryNavigationComp->dropdownDividerStyle);
            $I->wait(1);
            $I->selectOption($primaryNavigationComp->dropdownDividerStyle, 'Dotted');
            $I->wait(1);
            $I->click($primaryNavigationComp->desktop);
            $I->wait(2);
            $I->click($primaryNavigationComp->publishButton);
            $I->wait(3);
            $I->switchToIFrame($helper->frame);
            $I->wait(1);
            $I->moveMouseOver($primaryNavigationComp->home);
            $I->wait(2);
            $I->switchToIFrame();
            $I->amGoingTo('check on the front end');
            $I->amOnPage('/');
            $I->wait(2);
            $I->assertEquals($primaryNavigationComp->dropdownDividerStyle,$helper->dividerStyle);
            $I->wait(2);
            $I->moveMouseOver($primaryNavigationComp->home);
            $I->wait(2);

            $I->click($customize->url);
            $I->wait(2);
            $I->scrollTo($customize->header);
            $I->wait(2);
            $I->click($customize->header);
            $I->wait(2);
            $I->click($primaryNavigationComp->primaryNavButton);
            $I->scrollTo($primaryNavigationComp->dropdownDividerStyle);
            $I->wait(1);
            $I->selectOption($primaryNavigationComp->dropdownDividerStyle, 'Solid');
            $I->wait(1);
            $I->click($primaryNavigationComp->desktop);
            $I->wait(2);
            $I->click($primaryNavigationComp->publishButton);
            $I->wait(3);
            $I->switchToIFrame($helper->frame);
            $I->wait(1);
            $I->moveMouseOver($primaryNavigationComp->home);
            $I->wait(2);
            $I->switchToIFrame();
            $I->amGoingTo('check on the front end');
            $I->amOnPage('/');
            $I->wait(2);
            $I->assertEquals($primaryNavigationComp->dropdownDividerStyle,$helper->dividerStyle);
            $I->wait(2);
            $I->moveMouseOver($primaryNavigationComp->home);
            $I->wait(2);

            $I->amGoingTo('Check dropdown divider width settings for primary navigation');
            $I->click($customize->url);
            $I->wait(2);
            $I->scrollTo($customize->header);
            $I->wait(2);
            $I->click($customize->header);
            $I->wait(2);
            $I->click($primaryNavigationComp->primaryNavButton);
            $I->wait(2);
            $I->scrollTo($primaryNavigationComp->dDividerWidth);
            $I->wait(1);
             $I->fillField($primaryNavigationComp->dDividerWidth, '8');
              $I->wait(1);
              $I->click($primaryNavigationComp->desktop);
              $I->wait(2);
              $I->click($primaryNavigationComp->publishButton);
              $I->wait(3);
              $I->switchToIFrame($helper->frame);
              $I->wait(1);
              $I->moveMouseOver($primaryNavigationComp->home);
              $I->wait(2);
              $I->switchToIFrame();
              $I->amGoingTo('check on the front end');
              $I->amOnPage('/');
              $I->wait(2);
              $helper->_checkStyle($I,$helper->dividerWidth,'border-bottom','xpath','8px solid rgba(170, 170, 170, 0.2)');
                $I->wait(2);
              $I->moveMouseOver($primaryNavigationComp->home);
              $I->wait(2);

              $I->amGoingTo('check the  Dropdown Item color settings for primary navigation');
              $I->click($customize->url);
              $I->wait(2);
              $I->scrollTo($customize->header);
              $I->wait(2);
              $I->click($customize->header);
              $I->wait(2);
              $I->click($primaryNavigationComp->primaryNavButton);
              $I->wait(1);
              $I->scrollTo($primaryNavigationComp->selectDItemColor);
              $I->wait(1);
               $I->click($primaryNavigationComp->selectDItemColor);
                $I->wait(1);
                $I->click($primaryNavigationComp->dItemColor);
                $I->wait(1);
                $I->click($primaryNavigationComp->desktop);
                $I->wait(2);
                $I->click($primaryNavigationComp->publishButton);
                $I->wait(3);
                $I->switchToIFrame($helper->frame);
                $I->wait(1);
                $I->moveMouseOver($primaryNavigationComp->home);
                $I->wait(2);
                $I->switchToIFrame();
               $I->amGoingTo('check on the front end');
                $I->amOnPage('/');
                $I->wait(2);
                $helper->_checkStyle($I,$helper->dItemColor,'color','xpath','rgb(221, 51, 51)');
                $I->wait(2);
              $I->moveMouseOver($primaryNavigationComp->home);
              $I->wait(2);
      
                $I->amGoingTo('check the  Dropdown Itemhover color settings for primary navigation');
                $I->click($customize->url);
                $I->wait(2);
                $I->scrollTo($customize->header);
                $I->wait(2);
                $I->click($customize->header);
                $I->wait(2);
                $I->click($primaryNavigationComp->primaryNavButton);
                $I->wait(1);
                $I->scrollTo($primaryNavigationComp->selectDItemHover);
                $I->wait(1);
                 $I->click($primaryNavigationComp->selectDItemHover);
                  $I->wait(1);
                  $I->click($primaryNavigationComp->ditemHoverColor);
                  $I->wait(1);
                  $I->click($primaryNavigationComp->desktop);
                  $I->wait(2);
                  $I->click($primaryNavigationComp->publishButton);
                  $I->wait(3);
                  $I->switchToIFrame($helper->frame);
                $I->wait(1);
                $I->moveMouseOver($primaryNavigationComp->home);
                $I->wait(2);
                $I->switchToIFrame();
                  $I->amGoingTo('check on the front end');
                  $I->amOnPage('/');
                  $I->wait(2);
                  $helper->_checkStyle($I,$helper->dItemColor,'color','xpath','rgb(221, 51, 51)');
                  $I->wait(2);
                $I->moveMouseOver($primaryNavigationComp->home);
                $I->wait(2);

                  $I->amGoingTo('check the  Dropdown Active Item color settings for primary navigation');
                  $I->click($customize->url);
                  $I->wait(2);
                  $I->scrollTo($customize->header);
                  $I->wait(2);
                  $I->click($customize->header);
                  $I->wait(2);
                  $I->click($primaryNavigationComp->primaryNavButton);
                  $I->wait(1);
                  $I->scrollTo($primaryNavigationComp->SelectDActiveItemColor);
                  $I->wait(1);
                   $I->click($primaryNavigationComp->SelectDActiveItemColor);
                    $I->wait(1);
                    $I->click($primaryNavigationComp->dActiveItemColor);
                    $I->wait(1);
                    $I->click($primaryNavigationComp->desktop);
                    $I->wait(2);
                    $I->click($primaryNavigationComp->publishButton);
                    $I->wait(3);
                    $I->switchToIFrame($helper->frame);
                    $I->wait(1);
                    $I->moveMouseOver($primaryNavigationComp->home);
                    $I->wait(2);
                    $I->click($primaryNavigationComp->birds);
                    $I->wait(2);
                    $I->moveMouseOver($primaryNavigationComp->home);
                    $I->wait(3);
                    $I->switchToIFrame();
                    $I->amGoingTo('check on the front end');
                    $I->amOnPage('/');
                    $I->wait(2);
                    $helper->_checkStyle($I,$helper->dActiveItemColor,'color','xpath','rgb(130, 36, 227)');
                    $I->wait(2);
                     $I->moveMouseOver($primaryNavigationComp->home);
                     $I->wait(2);
                     $I->click($primaryNavigationComp->birds);
                    $I->wait(1);
                    $I->moveMouseOver($primaryNavigationComp->home);
                    $I->wait(2);
                    
                    $I->amGoingTo('check the  Dropdown background color settings for primary navigation');
                    $I->click($customize->url);
                    $I->wait(2);
                    $I->scrollTo($customize->header);
                    $I->wait(2);
                    $I->click($customize->header);
                    $I->wait(2);
                    $I->click($primaryNavigationComp->primaryNavButton);
                    $I->wait(1);
                    $I->scrollTo($primaryNavigationComp->selectDBgColor);
                    $I->wait(1);
                     $I->click($primaryNavigationComp->selectDBgColor);
                      $I->wait(1);
                      $I->click($primaryNavigationComp->dBgColor);
                      $I->wait(1);
                      $I->click($primaryNavigationComp->desktop);
                      $I->wait(2);
                      $I->click($primaryNavigationComp->publishButton);
                      $I->wait(3);
                      $I->switchToIFrame($helper->frame);
                      $I->wait(1);
                      $I->moveMouseOver($primaryNavigationComp->home);
                      $I->wait(2);
                      $I->switchToIFrame();
                      $I->amGoingTo('check on the front end');
                      $I->amOnPage('/');
                      $I->wait(2);
                      $helper->_checkStyle($I,$helper->dBgColor,'background','xpath','rgb(238, 238, 34) none repeat scroll 0% 0%');
                      $I->wait(2);
                      $I->moveMouseOver($primaryNavigationComp->home);
                      $I->wait(2);
                      
                      $I->amGoingTo('check the  Dropdown background hover color settings for primary navigation');
                      $I->click($customize->url);
                      $I->wait(2);
                      $I->scrollTo($customize->header);
                      $I->wait(2);
                      $I->click($customize->header);
                      $I->wait(2);
                      $I->click($primaryNavigationComp->primaryNavButton);
                      $I->wait(1);
                      $I->scrollTo($primaryNavigationComp->selectDBgHoverColor);
                      $I->wait(1);
                       $I->click($primaryNavigationComp->selectDBgHoverColor);
                        $I->wait(1);
                        $I->click($primaryNavigationComp->dBgHoverColor);
                        $I->wait(1);
                        $I->click($primaryNavigationComp->desktop);
                        $I->wait(2);
                        $I->click($primaryNavigationComp->publishButton);
                        $I->wait(3);
                        $I->switchToIFrame($helper->frame);
                        $I->wait(1);
                        $I->moveMouseOver($primaryNavigationComp->home);
                        $I->wait(2);
                        $I->moveMouseOver($primaryNavigationComp->birds);
                        $I->wait(2);
                        $I->switchToIFrame();
                        $I->amGoingTo('check on the front end');
                        $I->amOnPage('/');
                        $I->wait(2);
                        $helper->_checkStyle($I,$helper->dBgHover ,'background','xpath','rgba(0, 0, 0, 0) none repeat scroll 0% 0%');
                        $I->wait(2);
                        $I->moveMouseOver($primaryNavigationComp->home);
                        $I->wait(2);
                        $I->moveMouseOver($primaryNavigationComp->birds);
                        $I->wait(2);
                        
                        
                        $I->amGoingTo('check the  Dropdown divider color settings for primary navigation');
                        $I->click($customize->url);
                        $I->wait(2);
                        $I->scrollTo($customize->header);
                        $I->wait(2);
                        $I->click($customize->header);
                        $I->wait(2);
                        $I->click($primaryNavigationComp->primaryNavButton);
                        $I->wait(1);
                        $I->scrollTo($primaryNavigationComp->selectDDividerColor);
                        $I->wait(1);
                         $I->click($primaryNavigationComp->selectDDividerColor);
                          $I->wait(1);
                          $I->click($primaryNavigationComp->dDividercolor);
                          $I->wait(1);
                          $I->click($primaryNavigationComp->desktop);
                          $I->wait(2);
                          $I->click($primaryNavigationComp->publishButton);
                          $I->wait(3);
                          $I->switchToIFrame($helper->frame);
                        $I->wait(1);
                        $I->moveMouseOver($primaryNavigationComp->home);
                        $I->wait(2);
                        $I->switchToIFrame();
                        $I->amGoingTo('check on the front end');
                          $I->amOnPage('/');
                          $I->wait(2);
                          $helper->_checkStyle($I,$helper->dDividerColor ,'border-bottom','xpath','8px solid rgb(221, 153, 51)');
                        $I->wait(2);
                        $I->moveMouseOver($primaryNavigationComp->home);
                        $I->wait(2);

                        $I->amGoingTo('Logout');
                        $loginAndLogout->userLogout($I);
                        $I->wait(2);
    }
  public function TypographySettings(RespThemeTester $I, LogInAndLogOut $loginAndLogout, Customize $customize, PrimaryNavigationComp $primaryNavigationComp, CommonPrimarySettings $helper)
    {
       $I->amGoingTo('check the font family settings for primary navigation');
       $I->scrollTo($primaryNavigationComp->fontFamily);
       $I->wait(1);
       $I->selectOption($primaryNavigationComp->fontFamily, 'Times New Roman');
       $I->wait(1);
       $I->click($primaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($primaryNavigationComp->publishButton);
       $I->wait(3);
       $I->amGoingTo('check on the front end');
      $I->amOnPage('/');
      $I->wait(2);
      $helper->_checkStyle($I,$helper->typography,'font-family','xpath','Times New Roman');
       $I->wait(2);
         
      $I->click($customize->url);
      $I->wait(2);
      $I->scrollTo($customize->header);
      $I->wait(2);
      $I->click($customize->header);
      $I->wait(2);
      $I->click($primaryNavigationComp->primaryNavButton);
      $I->wait(1);
       $I->scrollTo($primaryNavigationComp->fontFamily);
       $I->wait(1);
       $I->selectOption($primaryNavigationComp->fontFamily, 'Aclonica');
       $I->wait(1);
       $I->click($primaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($primaryNavigationComp->publishButton);
       $I->wait(3);
       $I->amGoingTo('check on the front end');
      $I->amOnPage('/');
      $I->wait(2);
      $helper->_checkStyle($I,$helper->typography,'font-family','xpath','"Aclonica", sans-serif');
      $I->wait(2);
      

      $I->amGoingTo('check the font weight settings for primary navigation');
      $I->click($customize->url);
      $I->wait(2);
      $I->scrollTo($customize->header);
      $I->wait(2);
      $I->click($customize->header);
      $I->wait(2);
      $I->click($primaryNavigationComp->primaryNavButton);
      $I->wait(1);
       $I->scrollTo($primaryNavigationComp->fontWeight);
       $I->wait(1);
       $I->selectOption($primaryNavigationComp->fontWeight, 'Default');
       $I->wait(1);
       $I->click($primaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($primaryNavigationComp->publishButton);
       $I->wait(3);
       $I->amGoingTo('check on the front end');
      $I->amOnPage('/');
      $I->wait(2);
      $helper->_checkStyle($I,$helper->typography,'font-weight','xpath','600');
      $I->wait(2);
      
      $I->click($customize->url);
      $I->wait(2);
      $I->scrollTo($customize->header);
      $I->wait(2);
      $I->click($customize->header);
      $I->wait(2);
      $I->click($primaryNavigationComp->primaryNavButton);
      $I->wait(1);
       $I->scrollTo($primaryNavigationComp->fontWeight);
       $I->wait(1);
       $I->selectOption($primaryNavigationComp->fontWeight, 'Normal: 400');
       $I->wait(1);
       $I->click($primaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($primaryNavigationComp->publishButton);
       $I->wait(3);
       $I->amGoingTo('check on the front end');
      $I->amOnPage('/');
      $I->wait(2);
      $helper->_checkStyle($I,$helper->typography,'font-weight','xpath','400');
      $I->wait(2);
      
      $I->amGoingTo('check the font style settings for primary navigation');
      $I->click($customize->url);
      $I->wait(2);
      $I->scrollTo($customize->header);
      $I->wait(2);
      $I->click($customize->header);
      $I->wait(2);
      $I->click($primaryNavigationComp->primaryNavButton);
      $I->wait(1);
       $I->scrollTo($primaryNavigationComp->fontStyle);
       $I->wait(1);
       $I->selectOption($primaryNavigationComp->fontStyle, 'Normal');
       $I->wait(1);
       $I->click($primaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($primaryNavigationComp->publishButton);
       $I->wait(3);
       $I->amGoingTo('check on the front end');
      $I->amOnPage('/');
      $I->wait(2);
      $helper->_checkStyle($I,$helper->typography,'font-style','xpath','normal');
      $I->wait(2);
      
      $I->click($customize->url);
      $I->wait(2);
      $I->scrollTo($customize->header);
      $I->wait(2);
      $I->click($customize->header);
      $I->wait(2);
      $I->click($primaryNavigationComp->primaryNavButton);
      $I->wait(1);
       $I->scrollTo($primaryNavigationComp->fontStyle);
       $I->wait(1);
       $I->selectOption($primaryNavigationComp->fontStyle, 'Italic');
       $I->wait(1);
       $I->click($primaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($primaryNavigationComp->publishButton);
       $I->wait(3);
       $I->amGoingTo('check on the front end');
       $I->amOnPage('/');
       $I->wait(2);
       $helper->_checkStyle($I,$helper->typography,'font-style','xpath','italic');
       $I->wait(2);
       
      $I->amGoingTo('check the text transform settings for primary navigation');
      $I->click($customize->url);
      $I->wait(2);
      $I->scrollTo($customize->header);
      $I->wait(2);
      $I->click($customize->header);
      $I->wait(2);
      $I->click($primaryNavigationComp->primaryNavButton);
      $I->wait(1);
       $I->scrollTo($primaryNavigationComp->textTransform);
       $I->wait(1);
       $I->selectOption($primaryNavigationComp->textTransform, 'Capitalize');
       $I->wait(1);
       $I->click($primaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($primaryNavigationComp->publishButton);
       $I->wait(3);
       $I->amGoingTo('check on the front end');
      $I->amOnPage('/');
      $I->wait(2);
      $helper->_checkStyle($I,$helper->typography,'text-transform','xpath','capitalize');
      $I->wait(2);
     
      $I->click($customize->url);
      $I->wait(2);
      $I->scrollTo($customize->header);
      $I->wait(2);
      $I->click($customize->header);
      $I->wait(2);
      $I->click($primaryNavigationComp->primaryNavButton);
      $I->wait(1);
       $I->scrollTo($primaryNavigationComp->textTransform);
       $I->wait(1);
       $I->selectOption($primaryNavigationComp->textTransform, 'Lowercase');
       $I->wait(1);
       $I->click($primaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($primaryNavigationComp->publishButton);
       $I->wait(3);
       $I->amGoingTo('check on the front end');
      $I->amOnPage('/');
      $helper->_checkStyle($I,$helper->typography,'text-transform','xpath','lowercase');
      $I->wait(2);
      
      $I->click($customize->url);
      $I->wait(2);
      $I->scrollTo($customize->header);
      $I->wait(2);
      $I->click($customize->header);
      $I->wait(2);
      $I->click($primaryNavigationComp->primaryNavButton);
      $I->wait(1);
       $I->scrollTo($primaryNavigationComp->textTransform);
       $I->wait(1);
       $I->selectOption($primaryNavigationComp->textTransform, 'Uppercase');
       $I->wait(1);
       $I->click($primaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($primaryNavigationComp->publishButton);
       $I->wait(3);
       $I->amGoingTo('check on the front end');
      $I->amOnPage('/');
      $I->wait(2);
      $helper->_checkStyle($I,$helper->typography,'text-transform','xpath','uppercase');
      $I->wait(2);

    $I->amGoingTo('check the font size settings for primary navigation');
      $I->click($customize->url);
      $I->wait(2);
      $I->scrollTo($customize->header);
      $I->wait(2);
      $I->click($customize->header);
      $I->wait(2);
      $I->click($primaryNavigationComp->primaryNavButton);
      $I->wait(1);
       $I->scrollTo($primaryNavigationComp->fontSize);
       $I->wait(1);
       $I->fillField($primaryNavigationComp->fontSize, '20px');
       $I->wait(1);
       $I->click($primaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($primaryNavigationComp->publishButton);
       $I->wait(3);
       $I->amGoingTo('check on the front end');
      $I->amOnPage('/');
      $I->wait(2);
      $helper->_checkStyle($I,$helper->typography,'font-size','xpath','20px');
      $I->wait(2);

      $I->amGoingTo('check the line height settings for primary navigation');
      $I->click($customize->url);
      $I->wait(2);
      $I->scrollTo($customize->header);
      $I->wait(2);
      $I->click($customize->header);
      $I->wait(2);
      $I->click($primaryNavigationComp->primaryNavButton);
      $I->wait(1);
       $I->scrollTo($primaryNavigationComp->lineHeight);
       $I->wait(1);
       $I->fillField($primaryNavigationComp->lineHeight, '7');
       $I->wait(1);
       $I->click($primaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($primaryNavigationComp->publishButton);
       $I->wait(3);
       $I->amGoingTo('check on the front end');
      $I->amOnPage('/');
      $I->wait(2);
      $helper->_checkStyle($I,$helper->typography,'line-height','xpath','140px');
      $I->wait(2);
      
      $I->amGoingTo('check the letter spacing settings for primary navigation');
      $I->click($customize->url);
      $I->wait(2);
      $I->scrollTo($customize->header);
      $I->wait(2);
      $I->click($customize->header);
      $I->wait(2);
      $I->click($primaryNavigationComp->primaryNavButton);
      $I->wait(1);
       $I->scrollTo($primaryNavigationComp->letterSpacing);
       $I->wait(1);
       $I->fillField($primaryNavigationComp->letterSpacing, '4');
       $I->wait(1);
       $I->click($primaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($primaryNavigationComp->publishButton);
       $I->wait(3);
       $I->amGoingTo('check on the front end');
      $I->amOnPage('/');
      $I->wait(2);
      $helper->_checkStyle($I,$helper->typography,'letter-spacing','xpath','4px');
      $I->wait(2);

      $I->amGoingTo('Logout');
      $loginAndLogout->userLogout($I);
      $I->wait(2);
      
    }
public function DropdownTypographySettings(RespThemeTester $I, LogInAndLogOut $loginAndLogout, Customize $customize, PrimaryNavigationComp $primaryNavigationComp, CommonPrimarySettings $helper)
{
   $I->amGoingTo('check the dropdown font family settings for primary navigation');
       $I->scrollTo($primaryNavigationComp->dFontFamily);
       $I->wait(1);
       $I->selectOption($primaryNavigationComp->dFontFamily, 'Garamond');
       $I->wait(1);
       $I->click($primaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($primaryNavigationComp->publishButton);
       $I->wait(3);
       $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($primaryNavigationComp->home);
        $I->wait(2);
        $I->switchToIFrame();
       $I->amGoingTo('check on the front end');
      $I->amOnPage('/');
      $I->wait(2);
      $helper->_checkStyle($I,$helper->dTypography,'font-family','xpath','Garamond');
      $I->wait(2);
      $I->moveMouseOver($primaryNavigationComp->home);
        $I->wait(2);
     
      $I->click($customize->url);
      $I->wait(2);
      $I->scrollTo($customize->header);
      $I->wait(2);
      $I->click($customize->header);
      $I->wait(2);
      $I->click($primaryNavigationComp->primaryNavButton);
      $I->wait(1);
      $I->scrollTo($primaryNavigationComp->dFontFamily);
       $I->wait(1);
       $I->selectOption($primaryNavigationComp->dFontFamily, 'Aclonica');
       $I->wait(1);
       $I->click($primaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($primaryNavigationComp->publishButton);
       $I->wait(3);
       $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($primaryNavigationComp->home);
        $I->wait(2);
        $I->switchToIFrame(); 
      $I->amGoingTo('check on the front end');
      $I->amOnPage('/');
      $I->wait(2);
      $helper->_checkStyle($I,$helper->dTypography,'font-family','xpath','"Aclonica", sans-serif');
      $I->wait(2);
      $I->moveMouseOver($primaryNavigationComp->home);
        $I->wait(2);

      $I->amGoingTo('check the dropdown font weight settings for primary navigation');
      $I->click($customize->url);
      $I->wait(2);
      $I->scrollTo($customize->header);
      $I->wait(2);
      $I->click($customize->header);
      $I->wait(2);
      $I->click($primaryNavigationComp->primaryNavButton);
      $I->wait(1);
       $I->scrollTo($primaryNavigationComp->dFontWeight);
       $I->wait(1);
       $I->selectOption($primaryNavigationComp->dFontWeight, 'Default');
       $I->wait(1);
       $I->click($primaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($primaryNavigationComp->publishButton);
       $I->wait(3);
       $I->switchToIFrame($helper->frame);
       $I->wait(1);
       $I->moveMouseOver($primaryNavigationComp->home);
       $I->wait(2);
       $I->switchToIFrame();
      $I->amGoingTo('check on the front end');
      $I->amOnPage('/');
      $I->wait(2);
      $helper->_checkStyle($I,$helper->dTypography,'font-weight','xpath','400');
      $I->wait(2);
      $I->moveMouseOver($primaryNavigationComp->home);
        $I->wait(2);

      $I->click($customize->url);
      $I->wait(2);
      $I->scrollTo($customize->header);
      $I->wait(2);
      $I->click($customize->header);
      $I->wait(2);
      $I->click($primaryNavigationComp->primaryNavButton);
      $I->wait(1);
       $I->scrollTo($primaryNavigationComp->dFontWeight);
       $I->wait(1);
       $I->selectOption($primaryNavigationComp->dFontWeight, 'Normal: 400');
       $I->wait(1);
       $I->click($primaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($primaryNavigationComp->publishButton);
       $I->wait(3);
       $I->switchToIFrame($helper->frame);
       $I->wait(1);
       $I->moveMouseOver($primaryNavigationComp->home);
       $I->wait(2);
       $I->switchToIFrame();
      $I->amGoingTo('check on the front end');
      $I->amOnPage('/');
      $I->wait(2);
      $helper->_checkStyle($I,$helper->dTypography,'font-weight','xpath','400');
      $I->wait(2);
      $I->moveMouseOver($primaryNavigationComp->home);
        $I->wait(2);


      $I->amGoingTo('check the dropdown font style settings for primary navigation');
      $I->click($customize->url);
      $I->wait(2);
      $I->scrollTo($customize->header);
      $I->wait(2);
      $I->click($customize->header);
      $I->wait(2);
      $I->click($primaryNavigationComp->primaryNavButton);
      $I->wait(1);
       $I->scrollTo($primaryNavigationComp->dFontStyle);
       $I->wait(1);
       $I->selectOption($primaryNavigationComp->dFontStyle, 'Normal');
       $I->wait(1);
       $I->click($primaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($primaryNavigationComp->publishButton);
       $I->wait(3);
       $I->switchToIFrame($helper->frame);
       $I->wait(1);
       $I->moveMouseOver($primaryNavigationComp->home);
       $I->wait(2);
       $I->switchToIFrame();
      $I->amGoingTo('check on the front end');
      $I->amOnPage('/');
      $I->wait(2);
       $helper->_checkStyle($I,$helper->dTypography,'font-style','xpath','normal');
      $I->wait(2);
      $I->moveMouseOver($primaryNavigationComp->home);
        $I->wait(2);

      $I->click($customize->url);
      $I->wait(2);
      $I->scrollTo($customize->header);
      $I->wait(2);
      $I->click($customize->header);
      $I->wait(2);
      $I->click($primaryNavigationComp->primaryNavButton);
      $I->wait(1);
       $I->scrollTo($primaryNavigationComp->dFontStyle);
       $I->wait(1);
       $I->selectOption($primaryNavigationComp->dFontStyle, 'Italic');
       $I->wait(1);
       $I->click($primaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($primaryNavigationComp->publishButton);
       $I->wait(3);
       $I->switchToIFrame($helper->frame);
       $I->wait(1);
       $I->moveMouseOver($primaryNavigationComp->home);
       $I->wait(2);
       $I->switchToIFrame();
      $I->amGoingTo('check on the front end');
      $I->amOnPage('/');
      $I->wait(2);
      $helper->_checkStyle($I,$helper->dTypography,'font-style','xpath','italic');
      $I->wait(2);
      $I->moveMouseOver($primaryNavigationComp->home);
        $I->wait(2);


      $I->amGoingTo('check the drop down text transform settings for primary navigation');
      $I->click($customize->url);
      $I->wait(2);
      $I->scrollTo($customize->header);
      $I->wait(2);
      $I->click($customize->header);
      $I->wait(2);
      $I->click($primaryNavigationComp->primaryNavButton);
      $I->wait(1);
       $I->scrollTo($primaryNavigationComp->dTextTransform);
       $I->wait(1);
       $I->selectOption($primaryNavigationComp->dTextTransform, 'Capitalize');
       $I->wait(1);
       $I->click($primaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($primaryNavigationComp->publishButton);
       $I->wait(3);
       $I->switchToIFrame($helper->frame);
       $I->wait(1);
       $I->moveMouseOver($primaryNavigationComp->home);
       $I->wait(2);
       $I->switchToIFrame();
      $I->amGoingTo('check on the front end');
      $I->amOnPage('/');
      $I->wait(2);
      $helper->_checkStyle($I,$helper->dTypography,'text-transform','xpath','capitalize');
      $I->wait(2);
      $I->moveMouseOver($primaryNavigationComp->home);
        $I->wait(2);

      $I->click($customize->url);
      $I->wait(2);
      $I->scrollTo($customize->header);
      $I->wait(2);
      $I->click($customize->header);
      $I->wait(2);
      $I->click($primaryNavigationComp->primaryNavButton);
      $I->wait(1);
       $I->scrollTo($primaryNavigationComp->dTextTransform);
       $I->wait(1);
       $I->selectOption($primaryNavigationComp->dTextTransform, 'Lowercase');
       $I->wait(1);
       $I->click($primaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($primaryNavigationComp->publishButton);
       $I->wait(3);
       $I->switchToIFrame($helper->frame);
       $I->wait(1);
       $I->moveMouseOver($primaryNavigationComp->home);
       $I->wait(2);
       $I->switchToIFrame();
      $I->amGoingTo('check on the front end');
      $I->amOnPage('/');
      $I->wait(2);
      $helper->_checkStyle($I,$helper->dTypography,'text-transform','xpath','lowercase');
      $I->wait(2);
      $I->moveMouseOver($primaryNavigationComp->home);
        $I->wait(2);

      $I->click($customize->url);
      $I->wait(2);
      $I->scrollTo($customize->header);
      $I->wait(2);
      $I->click($customize->header);
      $I->wait(2);
      $I->click($primaryNavigationComp->primaryNavButton);
      $I->wait(1);
       $I->scrollTo($primaryNavigationComp->dTextTransform);
       $I->wait(1);
       $I->selectOption($primaryNavigationComp->dTextTransform, 'Uppercase');
       $I->wait(1);
       $I->click($primaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($primaryNavigationComp->publishButton);
       $I->wait(3);
       $I->switchToIFrame($helper->frame);
       $I->wait(1);
       $I->moveMouseOver($primaryNavigationComp->home);
       $I->wait(2);
       $I->switchToIFrame();
      $I->amGoingTo('check on the front end');
      $I->amOnPage('/');
      $helper->_checkStyle($I,$helper->dTypography,'text-transform','xpath','uppercase');
      $I->wait(2);
      $I->moveMouseOver($primaryNavigationComp->home);
        $I->wait(2);
      
      $I->amGoingTo('check the font size settings for primary navigation');
      $I->click($customize->url);
      $I->wait(2);
      $I->scrollTo($customize->header);
      $I->wait(2);
      $I->click($customize->header);
      $I->wait(2);
      $I->click($primaryNavigationComp->primaryNavButton);
      $I->wait(1);
       $I->scrollTo($primaryNavigationComp->dFontSize);
       $I->wait(1);
       $I->fillField($primaryNavigationComp->dFontSize, '16px');
       $I->wait(1);
       $I->click($primaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($primaryNavigationComp->publishButton);
       $I->wait(3);
       $I->switchToIFrame($helper->frame);
       $I->wait(1);
       $I->moveMouseOver($primaryNavigationComp->home);
       $I->wait(2);
       $I->switchToIFrame();
      $I->amGoingTo('check on the front end');
      $I->amOnPage('/');
      $helper->_checkStyle($I,$helper->dTypography,'font-size','xpath','16px');
      $I->wait(2);
      $I->moveMouseOver($primaryNavigationComp->home);
        $I->wait(2);
      
      $I->amGoingTo('check the line height settings for primary navigation');
      $I->click($customize->url);
      $I->wait(2);
      $I->scrollTo($customize->header);
      $I->wait(2);
      $I->click($customize->header);
      $I->wait(2);
      $I->click($primaryNavigationComp->primaryNavButton);
      $I->wait(1);
       $I->scrollTo($primaryNavigationComp->dLineHeight);
       $I->wait(1);
       $I->fillField($primaryNavigationComp->dLineHeight, '3');
       $I->wait(1);
       $I->click($primaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($primaryNavigationComp->publishButton);
       $I->wait(3);
       $I->switchToIFrame($helper->frame);
       $I->wait(1);
       $I->moveMouseOver($primaryNavigationComp->home);
       $I->wait(2);
       $I->switchToIFrame();
      $I->amGoingTo('check on the front end');
      $I->amOnPage('/');
      $I->wait(2);
      $helper->_checkStyle($I,$helper->dTypography,'line-height','xpath','3');
      $I->wait(2);
      $I->moveMouseOver($primaryNavigationComp->home);
        $I->wait(2);
      
      
      I->amGoingTo('check the letter spacing settings for primary navigation');
      $I->click($customize->url);
      $I->wait(2);
      $I->scrollTo($customize->header);
      $I->wait(2);
      $I->click($customize->header);
      $I->wait(2);
      $I->click($primaryNavigationComp->primaryNavButton);
      $I->wait(1);
       $I->scrollTo($primaryNavigationComp->dLetterSpacing);
       $I->wait(1);
       $I->fillField($primaryNavigationComp->dLetterSpacing, '2');
       $I->wait(1);
       $I->click($primaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($primaryNavigationComp->publishButton);
       $I->wait(3);
       $I->switchToIFrame($helper->frame);
       $I->wait(1);
       $I->moveMouseOver($primaryNavigationComp->home);
       $I->wait(2);
       $I->switchToIFrame();
       $I->amGoingTo('check on the front end');
      $I->amOnPage('/');
      $I->wait(2);
      $helper->_checkStyle($I,$helper->dTypography,'letter-spacing','xpath','2');
      $I->wait(2);
      $I->moveMouseOver($primaryNavigationComp->home);
        $I->wait(2);
      
        $I->amGoingTo('Logout');
        $loginAndLogout->userLogout($I);
        $I->wait(2);
    }
  }

