<?php
use \page\RespTheme\LogInAndLogOut;
use \page\RespTheme\SecondaryNavigationComp;
use \page\RespTheme\CommonPage;
use \Facebook\WebDriver\Remote\RemoteWebDriver;
use \Facebook\WebDriver\WebDriverBy;
use \Facebook\WebDriver\WebDriverKeys;

class SecondaryNavigationCest
{
    public function _before(RespThemeTester $I, LogInAndLogOut $loginAndLogout, SecondaryNavigationComp $secondaryNavigationComp, CommonPage $helper)
    {
          
        $I->amGoingTo('Login as Admin');
        $loginAndLogout->userLogin($I);

       
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(1);
    }
    // tests
    public function SecondaryNavigationStyle(RespThemeTester $I, LogInAndLogOut $loginAndLogout, SecondaryNavigationComp $secondaryNavigationComp, CommonPage $helper)
   {
    $I->amGoingTo('check the navigation style settings for secondary navigation');
    $I->click($secondaryNavigationComp->strechSMenu);
    $I->wait(2);
    $I->selectOption($secondaryNavigationComp->secondaryNavStyle, 'Standard');
    $I->wait(1);
    $I->click($secondaryNavigationComp->desktop);
    $I->wait(2);
    $I->click($secondaryNavigationComp->publishButton);
    $I->wait(3);
    $I->amGoingTo('check on the front end');
    $I->amOnPage('/');
    $I->wait(2);
    $I->assertEquals($secondaryNavigationComp->secondaryNavStyle,$helper->navigationStyle);
    $I->wait(2);
    $I->seeElement($secondaryNavigationComp->deskrow);
    $I->wait(2);
    
    $I->click($secondaryNavigationComp->url);
    $I->wait(2);
    $I->scrollTo($secondaryNavigationComp->header);
    $I->wait(2);
    $I->click($secondaryNavigationComp->header);
    $I->wait(2);
    $I->click($secondaryNavigationComp->secondaryNavButton);
    $I->wait(1);
    $I->selectOption($secondaryNavigationComp->secondaryNavStyle, 'Full height');
    $I->wait(1);
    $I->click($secondaryNavigationComp->desktop);
    $I->wait(2);
    $I->click($secondaryNavigationComp->publishButton);
    $I->wait(3);
    $I->amGoingTo('check on the front end');
    $I->amOnPage('/');
    $I->wait(2);
    $I->assertEquals($secondaryNavigationComp->secondaryNavStyle,$helper->navigationStyle);
    $I->wait(2);
    $I->seeElement($secondaryNavigationComp->deskrow);
    $I->wait(2);

    $I->click($secondaryNavigationComp->url);
    $I->wait(2);
    $I->scrollTo($secondaryNavigationComp->header);
    $I->wait(2);
    $I->click($secondaryNavigationComp->header);
    $I->wait(2);
    $I->click($secondaryNavigationComp->secondaryNavButton);
    $I->wait(1);
    $I->selectOption($secondaryNavigationComp->secondaryNavStyle, 'Underline');
    $I->wait(2);
    $I->click($secondaryNavigationComp->desktop);
    $I->wait(2);
    $I->click($secondaryNavigationComp->publishButton);
    $I->wait(3);
    $I->amGoingTo('check on the front end');
    $I->amOnPage('/');
    $I->wait(2);
    $I->assertEquals($secondaryNavigationComp->secondaryNavStyle,$helper->navigationStyle);
    $I->wait(2);
    $I->seeElement($secondaryNavigationComp->deskrow);
    $I->wait(2);

    $I->click($secondaryNavigationComp->url);
    $I->wait(2);
    $I->scrollTo($secondaryNavigationComp->header);
    $I->wait(2);
    $I->click($secondaryNavigationComp->header);
    $I->wait(2);
    $I->click($secondaryNavigationComp->secondaryNavButton);
    $I->wait(1);
    $I->selectOption($secondaryNavigationComp->secondaryNavStyle, 'Underline - Full height');
    $I->wait(2);
    $I->click($secondaryNavigationComp->desktop);
    $I->wait(2);
    $I->click($secondaryNavigationComp->publishButton);
    $I->wait(3);
    $I->amGoingTo('check on the front end');
    $I->amOnPage('/');
    $I->wait(2);
    $I->assertEquals($secondaryNavigationComp->secondaryNavStyle,$helper->navigationStyle);
    $I->wait(2);
    $I->seeElement($secondaryNavigationComp->deskrow);
    $I->wait(2);

    $I->amGoingTo('Logout');
    $loginAndLogout->userLogout($I);
    $I->wait(2);
   }
   public function ItemSettings(RespThemeTester $I, LogInAndLogOut $loginAndLogout,SecondaryNavigationComp $secondaryNavigationComp, CommonPage $helper)
    {
        $I->amGoingTo('check the Itemspacing and vertical itemspacing settings for seconary navigation');
        $I->fillField($secondaryNavigationComp->itemSpacing, '14');
        $I->wait(1);
        $I->fillField($secondaryNavigationComp->itemVerticalSpacing, '32');
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->itemspacing,'padding','xpath','32px 14px');
        $I->wait(2);

        $I->amGoingTo('check the Item color settings for secondary navigation');
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(1);
        $I->click($secondaryNavigationComp->selectItemColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->itemColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->sItemColor,'color','xpath','rgb(0, 0, 0)');
        $I->wait(2);

        $I->amGoingTo('check the Item hover  color settings for secondary navigation');
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->selectHoverItem);
        $I->wait(1);
        $I->click($secondaryNavigationComp->selectHoverItem);
        $I->wait(1);
        $I->click($secondaryNavigationComp->hoverItemColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->moreinfo);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->sItemHColor,'color','xpath','rgb(0, 0, 0)');
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->moreinfo);
        $I->wait(2);

        $I->amGoingTo('check the Active Item  color settings for secondary navigation');
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(1);
        $I->scrollTo($secondaryNavigationComp->selectActiveItemColor);
        $I->wait(2);
        $I->click($secondaryNavigationComp->selectActiveItemColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->activeItemColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->click($secondaryNavigationComp->moreinfo);
        $I->wait(3);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->sActiveItemColor,'color','xpath','rgb(0, 0, 0)');
        $I->wait(2);
        $I->click($secondaryNavigationComp->moreinfo);
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->moreinfo);
        $I->wait(2);

        $I->amGoingTo('check the Background color settings for secondary navigation');
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->selectBackgroundColor);
        $I->wait(2);
        $I->click($secondaryNavigationComp->selectBackgroundColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->backgroundColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->sBackgroundColor,'background','xpath','rgb(238, 238, 34) none repeat scroll 0% 0%');
        $I->wait(2);

        $I->amGoingTo('check the Background hover color settings for secondary navigation');
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(2);
        $I->click($secondaryNavigationComp->selectBgHoverColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->bgHoverColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->moreinfo);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->sBackgroundColor,'background','xpath','rgb(238, 238, 34) none repeat scroll 0% 0%');
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->moreinfo);
        $I->wait(2);

        $I->amGoingTo('check the Active background  color settings secondary navigation');
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->selectActiveBgColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->selectActiveBgColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->activeBgColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->click($secondaryNavigationComp->moreinfo);
        $I->wait(3);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->sBackgroundColor,'background','xpath','rgb(238, 238, 34) none repeat scroll 0% 0%');
        $I->wait(2);
        $I->click($secondaryNavigationComp->moreinfo);
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->moreinfo);
        $I->wait(2);

        $I->amGoingTo('Logout');
        $loginAndLogout->userLogout($I);
        $I->wait(2);
    }
    public function DropdownSettings(RespThemeTester $I, LogInAndLogOut $loginAndLogout, SecondaryNavigationComp $secondaryNavigationComp, CommonPage $helper)
    {
        $I->amGoingTo('check the dropdown reveal settings for secondary navigation');
        $I->scrollTo($secondaryNavigationComp->dropdownReveal);
        $I->selectOption($secondaryNavigationComp->dropdownReveal, 'Fade');
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $I->assertEquals($secondaryNavigationComp->dropdownReveal,$helper->dDReveal);
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);

        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->dropdownReveal);
        $I->selectOption($secondaryNavigationComp->dropdownReveal, 'Fade Up');
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $I->assertEquals($secondaryNavigationComp->dropdownReveal,$helper->dDReveal);
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);

        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->dropdownReveal);
        $I->selectOption($secondaryNavigationComp->dropdownReveal, 'Fade Down');
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $I->assertEquals($secondaryNavigationComp->dropdownReveal,$helper->dDReveal);
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);

        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->dropdownReveal);
        $I->selectOption($secondaryNavigationComp->dropdownReveal, 'None');
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $I->assertEquals($secondaryNavigationComp->dropdownReveal,$helper->dDReveal);
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);

        $I->amGoingTo('Check drop down width settings for secondary navigation');
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(2);
        $I->fillField($secondaryNavigationComp->dropdownWidth, '213');
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->dWidth,'width','xpath','213px');
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2); 

        $I->amGoingTo('Check dropdown vertical spacing settings for secondary navigation');
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->dropdownVerticalSpacing);
        $I->wait(1);
        $I->fillField($secondaryNavigationComp->dropdownVerticalSpacing, '21');
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->dVerSpacing,'padding-top','xpath','21px');
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2); 

        $I->amGoingTo('Check dropdown item divider style settings for secondary navigation');
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->dropdownDividerStyle);
        $I->wait(1);
        $I->selectOption($secondaryNavigationComp->dropdownDividerStyle, 'Dashed');
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->assertEquals($secondaryNavigationComp->dropdownDividerStyle,$helper->dividerStyle);
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
         
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->dropdownDividerStyle);
        $I->wait(1);
        $I->selectOption($secondaryNavigationComp->dropdownDividerStyle, 'Dotted');
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->assertEquals($secondaryNavigationComp->dropdownDividerStyle,$helper->dividerStyle);
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);

        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->dropdownDividerStyle);
        $I->wait(1);
        $I->selectOption($secondaryNavigationComp->dropdownDividerStyle, 'Solid');
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->assertEquals($secondaryNavigationComp->dropdownDividerStyle,$helper->dividerStyle);
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);

        $I->amGoingTo('Check dropdown divider width settings for secondary navigation');
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->dDividerWidth);
        $I->wait(1);
        $I->fillField($secondaryNavigationComp->dDividerWidth, '8');
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->dividerWidth,'border-bottom','xpath','8px solid rgba(170, 170, 170, 0.2)');
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);

        $I->amGoingTo('check the  Dropdown Item color settings for secondary navigation');
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(1);
        $I->scrollTo($secondaryNavigationComp->selectDItemColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->selectDItemColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->dItemColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->dItemColor,'color','xpath','rgb(0, 0, 0)');
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);

        $I->amGoingTo('check the  Dropdown Itemhover color settings for secondary navigation');
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(1);
        $I->scrollTo($secondaryNavigationComp->selectDItemHover);
        $I->wait(1);
        $I->click($secondaryNavigationComp->selectDItemHover);
        $I->wait(1);
        $I->click($secondaryNavigationComp->ditemHoverColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->editprofile);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->dItemColor,'color','xpath','rgb(0, 0, 0)');
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->editprofile);
        $I->wait(2);

        $I->amGoingTo('check the  Dropdown Active Item color settings for secondary navigation');
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(1);
        $I->scrollTo($secondaryNavigationComp->SelectDActiveItemColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->SelectDActiveItemColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->dActiveItemColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->click($secondaryNavigationComp->editprofile);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->dItemColor,'color','xpath','rgb(0, 0, 0)');
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->click($secondaryNavigationComp->editprofile);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);

        $I->amGoingTo('check the  Dropdown background color settings for secondary navigation');
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(1);
        $I->scrollTo($secondaryNavigationComp->selectDBgColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->selectDBgColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->dBgColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->dBgColor,'background','xpath','rgb(238, 238, 34) none repeat scroll 0% 0%');
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);

        
        $I->amGoingTo('check the  Dropdown background hover color settings for secondary navigation');
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(1);
        $I->scrollTo($secondaryNavigationComp->selectDBgHoverColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->selectDBgHoverColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->dBgHoverColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->logout);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->dBgHover ,'background','xpath','rgba(0, 0, 0, 0) none repeat scroll 0% 0%');
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->logout);
        $I->wait(2);

        $I->amGoingTo('check the  Dropdown Active Background color settings for secondary navigation');
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(1);
        $I->scrollTo($secondaryNavigationComp->SelectDActiveBgColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->SelectDActiveBgColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->dActiveBgColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->click($secondaryNavigationComp->editprofile);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->dActiveBg,'color','xpath','rgb(0, 0, 0)');
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->click($secondaryNavigationComp->editprofile);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);

        $I->amGoingTo('check the  Dropdown divider color settings for secondary navigation');
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(1);
        $I->scrollTo($secondaryNavigationComp->selectDDividerColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->selectDDividerColor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->dDividercolor);
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->dDividerColor ,'border-bottom','xpath','8px solid rgb(30, 115, 190)');
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);

        $I->amGoingTo('Logout');
        $loginAndLogout->userLogout($I);
        $I->wait(2);

    }
    public function TypographySettings(RespThemeTester $I, LogInAndLogOut $loginAndLogout, SecondaryNavigationComp $secondaryNavigationComp, CommonPage $helper)
    {
       $I->amGoingTo('check the font family settings for secondary navigation');
       $I->scrollTo($secondaryNavigationComp->fontFamily);
       $I->wait(1);
       $I->selectOption($secondaryNavigationComp->fontFamily, 'Times New Roman');
       $I->wait(1);
       $I->click($secondaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($secondaryNavigationComp->publishButton);
       $I->wait(3);
       $I->amGoingTo('check on the front end');
       $I->amOnPage('/');
       $I->wait(2);
       $helper->_checkStyle($I,$helper->typography,'font-family','xpath','Times New Roman');
       $I->wait(2);

       $I->click($secondaryNavigationComp->url);
       $I->wait(2);
       $I->scrollTo($secondaryNavigationComp->header);
       $I->wait(2);
       $I->click($secondaryNavigationComp->header);
       $I->wait(2);
       $I->click($secondaryNavigationComp->secondaryNavButton);
       $I->wait(1);
       $I->scrollTo($secondaryNavigationComp->fontFamily);
       $I->wait(1);
       $I->selectOption($secondaryNavigationComp->fontFamily, 'Aclonica');
       $I->wait(1);
       $I->click($secondaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($secondaryNavigationComp->publishButton);
       $I->wait(3);
       $I->amGoingTo('check on the front end');
       $I->amOnPage('/');
       $I->wait(2);
       $helper->_checkStyle($I,$helper->typography,'font-family','xpath','"Aclonica", sans-serif');
       $I->wait(2);

       $I->amGoingTo('check the font weight settings for secondary navigation');
       $I->click($secondaryNavigationComp->url);
       $I->wait(2);
       $I->scrollTo($secondaryNavigationComp->header);
       $I->wait(2);
       $I->click($secondaryNavigationComp->header);
       $I->wait(2);
       $I->click($secondaryNavigationComp->secondaryNavButton);
       $I->wait(1);
       $I->scrollTo($secondaryNavigationComp->fontWeight);
       $I->wait(1);
       $I->selectOption($secondaryNavigationComp->fontWeight, 'Default');
       $I->wait(1);
       $I->click($secondaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($secondaryNavigationComp->publishButton);
       $I->wait(3);
       $I->amGoingTo('check on the front end');
       $I->amOnPage('/');
       $I->wait(2);
       $helper->_checkStyle($I,$helper->typography,'font-weight','xpath','600');
       $I->wait(2);

       $I->click($secondaryNavigationComp->url);
       $I->wait(2);
       $I->scrollTo($secondaryNavigationComp->header);
       $I->wait(2);
       $I->click($secondaryNavigationComp->header);
       $I->wait(2);
       $I->click($secondaryNavigationComp->secondaryNavButton);
       $I->wait(1);
       $I->scrollTo($secondaryNavigationComp->fontWeight);
       $I->wait(1);
       $I->selectOption($secondaryNavigationComp->fontWeight, 'Normal: 400');
       $I->wait(1);
       $I->click($secondaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($secondaryNavigationComp->publishButton);
       $I->wait(3);
       $I->amGoingTo('check on the front end');
       $I->amOnPage('/');
       $I->wait(2);
       $helper->_checkStyle($I,$helper->typography,'font-weight','xpath','400');
       $I->wait(2);

       $I->amGoingTo('check the  font style settings for secondary navigation');
       $I->click($secondaryNavigationComp->url);
       $I->wait(2);
       $I->scrollTo($secondaryNavigationComp->header);
       $I->wait(2);
       $I->click($secondaryNavigationComp->header);
       $I->wait(2);
       $I->click($secondaryNavigationComp->secondaryNavButton);
       $I->wait(1);
       $I->scrollTo($secondaryNavigationComp->fontStyle);
       $I->wait(1);
       $I->selectOption($secondaryNavigationComp->fontStyle, 'Normal');
       $I->wait(1);
       $I->click($secondaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($secondaryNavigationComp->publishButton);
       $I->wait(3);
       $I->amGoingTo('check on the front end');
       $I->amOnPage('/');
       $I->wait(2);
       $helper->_checkStyle($I,$helper->typography,'font-style','xpath','normal');
       $I->wait(2);

       $I->click($secondaryNavigationComp->url);
       $I->wait(2);
       $I->scrollTo($secondaryNavigationComp->header);
       $I->wait(2);
       $I->click($secondaryNavigationComp->header);
       $I->wait(2);
       $I->click($secondaryNavigationComp->secondaryNavButton);
       $I->wait(1);
       $I->scrollTo($secondaryNavigationComp->fontStyle);
       $I->wait(1);
       $I->selectOption($secondaryNavigationComp->fontStyle, 'Italic');
       $I->wait(1);
       $I->click($secondaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($secondaryNavigationComp->publishButton);
       $I->wait(3);
       $I->amGoingTo('check on the front end');
       $I->amOnPage('/');
       $I->wait(2);
       $helper->_checkStyle($I,$helper->typography,'font-style','xpath','italic');
       $I->wait(2);

       $I->amGoingTo('check the  text transform settings for secondary navigation');
       $I->click($secondaryNavigationComp->url);
       $I->wait(2);
       $I->scrollTo($secondaryNavigationComp->header);
       $I->wait(2);
       $I->click($secondaryNavigationComp->header);
       $I->wait(2);
       $I->click($secondaryNavigationComp->secondaryNavButton);
       $I->wait(1);
       $I->scrollTo($secondaryNavigationComp->textTransform);
       $I->wait(1);
       $I->selectOption($secondaryNavigationComp->textTransform, 'Capitalize');
       $I->wait(1);
       $I->click($secondaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($secondaryNavigationComp->publishButton);
       $I->wait(3);
       $I->amGoingTo('check on the front end');
       $I->amOnPage('/');
       $I->wait(2);
       $helper->_checkStyle($I,$helper->typography,'text-transform','xpath','capitalize');
       $I->wait(2);

       $I->click($secondaryNavigationComp->url);
       $I->wait(2);
       $I->scrollTo($secondaryNavigationComp->header);
       $I->wait(2);
       $I->click($secondaryNavigationComp->header);
       $I->wait(2);
       $I->click($secondaryNavigationComp->secondaryNavButton);
       $I->wait(1);
       $I->scrollTo($secondaryNavigationComp->textTransform);
       $I->wait(1);
       $I->selectOption($secondaryNavigationComp->textTransform, 'Lowercase');
       $I->wait(1);
       $I->click($secondaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($secondaryNavigationComp->publishButton);
       $I->wait(3);
       $I->amGoingTo('check on the front end');
       $I->amOnPage('/');
       $I->wait(2);
       $helper->_checkStyle($I,$helper->typography,'text-transform','xpath','lowercase');
       $I->wait(2);

       $I->click($secondaryNavigationComp->url);
       $I->wait(2);
       $I->scrollTo($secondaryNavigationComp->header);
       $I->wait(2);
       $I->click($secondaryNavigationComp->header);
       $I->wait(2);
       $I->click($secondaryNavigationComp->secondaryNavButton);
       $I->wait(1);
       $I->scrollTo($secondaryNavigationComp->textTransform);
       $I->wait(1);
       $I->selectOption($secondaryNavigationComp->textTransform, 'Uppercase');
       $I->wait(1);
       $I->click($secondaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($secondaryNavigationComp->publishButton);
       $I->wait(3);
       $I->amGoingTo('check on the front end');
       $I->amOnPage('/');
       $I->wait(2);
       $helper->_checkStyle($I,$helper->typography,'text-transform','xpath','uppercase');
       $I->wait(2);

       $I->amGoingTo('check the font size settings for secondary navigation');
       $I->click($secondaryNavigationComp->url);
       $I->wait(2);
       $I->scrollTo($secondaryNavigationComp->header);
       $I->wait(2);
       $I->click($secondaryNavigationComp->header);
       $I->wait(2);
       $I->click($secondaryNavigationComp->secondaryNavButton);
       $I->wait(1);
       $I->scrollTo($secondaryNavigationComp->fontSize);
       $I->wait(1);
       $I->fillField($secondaryNavigationComp->fontSize, '7px');
       $I->wait(1);
       $I->click($secondaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($secondaryNavigationComp->publishButton);
       $I->wait(3);
       $I->amGoingTo('check on the front end');
       $I->amOnPage('/');
       $I->wait(2);
       $helper->_checkStyle($I,$helper->typography,'font-size','xpath','7px');
       $I->wait(2);

       $I->amGoingTo('check the line height settings for secondary navigation');
       $I->click($secondaryNavigationComp->url);
       $I->wait(2);
       $I->scrollTo($secondaryNavigationComp->header);
       $I->wait(2);
       $I->click($secondaryNavigationComp->header);
       $I->wait(2);
       $I->click($secondaryNavigationComp->secondaryNavButton);
       $I->wait(1);
       $I->scrollTo($secondaryNavigationComp->lineHeight);
       $I->wait(1);
       $I->fillField($secondaryNavigationComp->lineHeight, '2');
       $I->wait(1);
       $I->click($secondaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($secondaryNavigationComp->publishButton);
       $I->wait(3);
       $I->amGoingTo('check on the front end');
       $I->amOnPage('/');
       $I->wait(2);
       $helper->_checkStyle($I,$helper->typography,'line-height','xpath','14px');
       $I->wait(2);

       $I->amGoingTo('check the letter spacing settings for secondary navigation');
       $I->click($secondaryNavigationComp->url);
       $I->wait(2);
       $I->scrollTo($secondaryNavigationComp->header);
       $I->wait(2);
       $I->click($secondaryNavigationComp->header);
       $I->wait(2);
       $I->click($secondaryNavigationComp->secondaryNavButton);
       $I->wait(1);
       $I->scrollTo($secondaryNavigationComp->letterSpacing);
       $I->wait(1);
       $I->fillField($secondaryNavigationComp->letterSpacing, '4');
       $I->wait(1);
       $I->click($secondaryNavigationComp->desktop);
       $I->wait(2);
       $I->click($secondaryNavigationComp->publishButton);
       $I->wait(3);
       $I->amGoingTo('check on the front end');
       $I->amOnPage('/');
       $I->wait(2);
       $helper->_checkStyle($I,$helper->typography,'letter-spacing','xpath','4px');
       $I->wait(2);

       $I->amGoingTo('Logout');
       $loginAndLogout->userLogout($I);
       $I->wait(2);
    }
    public function DropdownTypographySettings(RespThemeTester $I, LogInAndLogOut $loginAndLogout,  SecondaryNavigationComp $secondaryNavigationComp, CommonPage $helper)
    { 
        $I->amGoingTo('check the dropdown font family settings for secondary navigation');
        $I->scrollTo($secondaryNavigationComp->dFontFamily);
        $I->wait(1);
        $I->selectOption($secondaryNavigationComp->dFontFamily, 'Garamond');
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->dTypography,'font-family','xpath','Garamond');
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(1);
        $I->scrollTo($secondaryNavigationComp->dFontFamily);
        $I->wait(1);
        $I->selectOption($secondaryNavigationComp->dFontFamily, 'Times New Roman');
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->dTypography,'font-family','xpath','Times New Roman');
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);

        $I->amGoingTo('check the dropdown font weight settings for secondary navigation');
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(1);
        $I->scrollTo($secondaryNavigationComp->dFontWeight);
        $I->wait(1);
        $I->selectOption($secondaryNavigationComp->dFontWeight, 'Bold: 700');
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->dTypography,'font-weight','xpath','700');
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);

        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(1);
        $I->scrollTo($secondaryNavigationComp->dFontWeight);
        $I->wait(1);
        $I->selectOption($secondaryNavigationComp->dFontWeight, 'Black: 900');
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->dTypography,'font-weight','xpath','900');
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);

        $I->amGoingTo('check the dropdown font style settings for secondary navigation');
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(1);
        $I->scrollTo($secondaryNavigationComp->dFontStyle);
        $I->wait(1);
        $I->selectOption($secondaryNavigationComp->dFontStyle, 'Normal');
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->dTypography,'font-style','xpath','normal');
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);

        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(1);
        $I->scrollTo($secondaryNavigationComp->dFontStyle);
        $I->wait(1);
        $I->selectOption($secondaryNavigationComp->dFontStyle, 'Italic');
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->dTypography,'font-style','xpath','italic');
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);

        $I->amGoingTo('check the drop down text transform settings for secondary navigation');
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(1);
        $I->scrollTo($secondaryNavigationComp->dTextTransform);
        $I->wait(1);
        $I->selectOption($secondaryNavigationComp->dTextTransform, 'Capitalize');
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->dTypography,'text-transform','xpath','capitalize');
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);

        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(1);
        $I->scrollTo($secondaryNavigationComp->dTextTransform);
        $I->wait(1);
        $I->selectOption($secondaryNavigationComp->dTextTransform, 'Uppercase');
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->dTypography,'text-transform','xpath','uppercase');
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);

        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(1);
        $I->scrollTo($secondaryNavigationComp->dTextTransform);
        $I->wait(1);
        $I->selectOption($secondaryNavigationComp->dTextTransform, 'Lowercase');
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->dTypography,'text-transform','xpath','lowercase');
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);

        $I->amGoingTo('check the dropdown font size settings for secondary navigation');
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(1);
        $I->scrollTo($secondaryNavigationComp->dFontSize);
        $I->wait(1);
        $I->fillField($secondaryNavigationComp->dFontSize, '16px');
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $helper->_checkStyle($I,$helper->dTypography,'font-size','xpath','16px');
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);

        $I->amGoingTo('check the dropdown line height settings for secondary navigation');
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(1);
        $I->scrollTo($secondaryNavigationComp->dLineHeight);
        $I->wait(1);
        $I->fillField($secondaryNavigationComp->dLineHeight, '3');
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->dTypography,'line-height','xpath','48px');
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        
        $I->amGoingTo('check the letter spacing settings for secondary navigation');
        $I->click($secondaryNavigationComp->url);
        $I->wait(2);
        $I->scrollTo($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->header);
        $I->wait(2);
        $I->click($secondaryNavigationComp->secondaryNavButton);
        $I->wait(1);
        $I->scrollTo($secondaryNavigationComp->dLetterSpacing);
        $I->wait(1);
        $I->fillField($secondaryNavigationComp->dLetterSpacing, '2');
        $I->wait(1);
        $I->click($secondaryNavigationComp->desktop);
        $I->wait(2);
        $I->click($secondaryNavigationComp->publishButton);
        $I->wait(3);
        $I->switchToIFrame($helper->frame);
        $I->wait(1);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);
        $I->switchToIFrame();
        $I->amGoingTo('check on the front end');
        $I->amOnPage('/');
        $I->wait(2);
        $helper->_checkStyle($I,$helper->dTypography,'letter-spacing','xpath','2px');
        $I->wait(2);
        $I->moveMouseOver($secondaryNavigationComp->settings);
        $I->wait(2);

        $I->amGoingTo('Logout');
        $loginAndLogout->userLogout($I);
        $I->wait(2);
    }
}
