<?php
/**
 * Functions Install
 *
 * Functions for installation & activation
 *
 * @package        Responsive
 * @license        license.txt
 * @copyright      2014 CyberChimps
 * @since          1.9.5.0
 *
 * Please do not edit this file. This file is part of the Responsive and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

/**
 * Hide core theme activation message.
 *
 * @since    1.9.5.0
 */
function responsive_admin_css() { ?>
	<style>
	.themes-php #message2 {
		display: none;
	}
	.themes-php div.activation a {
		text-decoration: none;
	}
	.addon-count
	{
		display:inline-block;
		z-index:26;
		margin:1px 0 0 5px;
		padding:0 6px;
		border-radius:10px;
		color:#fff;
		background-color:#d54e21;
		font-size:9px;
		line-height:17px;
		vertical-align:top;
	}
	</style>
	<?php
}
add_action( 'admin_head', 'responsive_admin_css' );
